
ALTER TABLE Users
DROP CONSTRAINT PK__Users__77222459A05E2393

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT CH_UsernameAtLeast3Symbols CHECK (LEN(Username) >= 3)
 